# Arifmetik amallar

---



                                                                                                                 created by Navruzbek_Abduganiyev

In [3]:
import numpy as np

In [4]:
#massivga yo'naltirilgan dasturlash
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(6,12).reshape(2,3)
print(arr1,end="\n")
print(arr2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [5]:
#kopaytiramiz 
arr1 * arr2

array([[ 0,  7, 16],
       [27, 40, 55]])

In [6]:
#qoshamiz
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [7]:
#ayiramiz
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [10]:
#bolamiz 
arr1 / arr2

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [11]:
#kvadratga oshiramiz
arr1**arr2

array([[       0,        1,      256],
       [   19683,  1048576, 48828125]])

In [1]:
 # Hulosa qilib aytadigan bolsak , arifmetik amallarni oddiy hisoblashdek qilishimiz mukin
 

# Massivga yo'naltirilgan dasturlash
**Matematik va Statik amallarni qo'llash**



*   sum
*   mean

*   std, var

*   min, max

*   cumsum
*   cumprod





In [4]:
#statik amallarni qo'llash
arr=np.random.randn(4,5)
arr

array([[ 0.73674875,  0.24687243,  0.0710977 , -0.67660165, -1.25077757],
       [-2.67357514,  0.48302884,  1.20478477, -0.45239058,  0.88705674],
       [-0.42088916,  0.04286222, -0.01504751, -0.7272064 , -0.12637005],
       [-0.48947492,  0.73331215,  0.09054411, -0.51575474, -0.76548494]])

In [5]:
np.sum(arr)  # arr massivlarni yig'indisini qaytaradi

-3.6172649479108765

In [6]:
np.sum(arr)

-3.6172649479108765

In [7]:
arr.sum()

-3.6172649479108765

In [ ]:
#  3 hil usulda statik amalllarni qo'llashimiz mumkin

In [8]:
#shunungdek ushbu amallarni ustularga ham bersak ham bo'ladi

In [10]:
arr.sum(axis=1)

array([-0.87266034, -0.55109536, -1.2466509 , -0.94685834])

In [15]:
#  mean() bu o'racha qiymat
#  mean()  metodini ham ko'radigan bo'lsak
arr.mean()  # massiv  barcha elementlarini yig'indisini umumiy soniga bo'ladi

-0.18086324739554382

In [14]:
arr.mean(axis=0)  #bunda ham ustun yoki qatorlar uchun alohida qiymatlar chiqarish mumkin.axis=1 yoki axis=0 berib

array([-0.71179762,  0.37651891,  0.33784477, -0.59298834, -0.31389396])

In [17]:
#cumsum berilgan sonlar ketma-ketligida uzidan oldingi kelgan sonlar yig'indisiga teng qiymatlar chiqaradi
arr=np.arange(6)
arr


array([0, 1, 2, 3, 4, 5])

In [19]:
arr.cumsum()   # hisob kitobini uzingiz qilib olasiz

array([ 0,  1,  3,  6, 10, 15])

In [20]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0])

**Massivga yo'naltirilgan dasturlash** -- 
tartiblash sortlash

In [26]:
arr=np.random.randn(7)
arr

array([-0.82748001,  0.66214625,  2.08607576,  1.11186326,  0.17767062,
        1.63620377, -1.83873546])

In [31]:
sorted_arr=np.sort(arr)
sorted_arr

array([-1.83873546, -0.82748001,  0.17767062,  0.66214625,  1.11186326,
        1.63620377,  2.08607576])

In [33]:
arr=np.random.randint(12,size=(3,4))
arr

array([[ 2, 10,  8,  4],
       [ 2, 11,  3,  0],
       [ 1,  3,  7, 11]])

In [37]:
np.sort(arr,axis=0)  # bunda ham ustun yoki satrlar bo'yicha tartiblash mumkin axis

array([[ 0,  2,  3, 10],
       [ 1,  3,  7, 11],
       [ 2,  4,  8, 11]])

In [43]:
#   teskari tartibda tartiblash uchun
arr=np.random.randn(4)
arr

array([-0.47215578, -3.0394962 , -0.72329373, -2.49491903])

In [46]:
-np.sort(-arr)  #teskari tartibda tartiblash

array([-0.47215578, -0.72329373, -2.49491903, -3.0394962 ])

**unique,setdiff1d va in1d**  -- massivga yo'naltirilgan dasturlash

In [48]:
arr=np.array(['osmon','dasturlash','malaka','bilm','yulduz','dasturlash'])
arr

array(['osmon', 'dasturlash', 'malaka', 'bilm', 'yulduz', 'dasturlash'],
      dtype='<U10')

In [53]:
np.unique(arr)  #massivdagi takrorlanmas qiymatlarni chiqaradi

array(['bilm', 'dasturlash', 'malaka', 'osmon', 'yulduz'], dtype='<U10')

In [54]:
arr1=np.array([1,2,56,59,89,6])
arr2=np.array([656,25,56,2,1])


In [57]:
np.in1d(arr1,arr2) # arr1 dagi qiymatlarni arr2 ga solishtiradi,va bool tipida qiymat qaytaradi

array([ True,  True,  True, False, False, False])

In [63]:
np.setdiff1d(arr2,arr1)   #arr2 dagi arr1 da yo'q qiymatlarni chiqaradi

array([ 25, 656])