## N o'lchamli massivlarga ishlov berish 2

---


                                                                                                                created by Navruzbek_Abduganiyev

**Array o'qlarini almashtirish**-swapping axes or transpose

In [2]:
import numpy as np

In [16]:
#deylik m,n mo'lchamili massiv yaratamiz
arr=np.random.randint(10,size=(4,5))
arr

array([[9, 1, 3, 0, 6],
       [4, 4, 4, 7, 3],
       [1, 6, 1, 6, 7],
       [2, 8, 5, 0, 0]])

In [18]:
#shaklini ko'ramiz
arr.shape

(4, 5)

In [17]:
#ushbu massiv o'qlarini ustunlarga almashtirish talab qilinsin,buning uchun .T metodidan foydalanamiz
arr1=arr.T
arr1

array([[9, 4, 1, 2],
       [1, 4, 6, 8],
       [3, 4, 1, 5],
       [0, 7, 6, 0],
       [6, 3, 7, 0]])

In [19]:
#shaklini ko'ramiz
arr1.shape

(5, 4)

In [23]:
#shuningdek bo'shqa metoddan ham foydalanishimiz mumkin
arr.swapaxes(1,0)

array([[9, 4, 1, 2],
       [1, 4, 6, 8],
       [3, 4, 1, 5],
       [0, 7, 6, 0],
       [6, 3, 7, 0]])

In [25]:
arr

array([[9, 1, 3, 0, 6],
       [4, 4, 4, 7, 3],
       [1, 6, 1, 6, 7],
       [2, 8, 5, 0, 0]])

In [24]:
arr.swapaxes(0,1)   #huddi transpose ishini qilib beradi

array([[9, 4, 1, 2],
       [1, 4, 6, 8],
       [3, 4, 1, 5],
       [0, 7, 6, 0],
       [6, 3, 7, 0]])

In [28]:
np.dot(arr,arr.T)  # bu yerda hech qanday qo'rqinchli narsa bo'layotgani yo'q.<dot> ko'pytirish mmetodi.
#chiziqli algebrada massivlarni bir-biriga ko'paytirayotganda birining ustun soni,ikkinchisining satrlar soniga teng bo'lishi kerak

array([[127,  70,  60,  41],
       [ 70, 106,  95,  60],
       [ 60,  95, 123,  55],
       [ 41,  60,  55,  93]])

In [30]:
np.dot(2,5)  #huddi 2*5 day ayon::)

10

# **Universal funksiyalar bilan ishlashni o'rganamiz**

---
Unary -(bitta argument qabul qiluvchi funksiyalar)


In [32]:
#bunda faqat bitta massiv qabul qiladi
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
#sqrt,square,log,sign,modf,exp,isnan va bir qancha unary funksiyalar bor,ulardan maqsadga qarab ishlatiladi
np.square(arr)   # massivning qar bir elemntidan kv chiqarib beradi

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])



1.   sqrt-kvadrat ildizini qaytaradi
2.   square - kvadratini qaytaradi


3.   log e - asosga ko'ra hisoblaydi har bir qiymatni
4.   sign - son manfiy bolsa -1,0 ga teng bolsa 0,musbat bolsa 1 qaytaradi
5.   modf - sonning qoldiq va asos qismlarini ikkiga ajratadi
6.   exp - e darajasiga kora hisoblaydi
7.   isnan - nan qiymatlarni true aks holda false qaytaradi

In [37]:
#tepadagi barcha usullarni uzingiz sinab ko'rishingiz mumkin,biz modf bilan tanishammiz
arr=np.random.randn(4,5)
arr

array([[-0.44908045, -0.85888059,  0.40496453, -0.02762133,  1.06576493],
       [ 0.5258603 , -0.65922439,  2.19579734, -0.23635479,  0.66762795],
       [ 0.53682092, -1.2703466 , -1.23485728,  1.05613417, -0.41367831],
       [ 0.13546575, -1.60136672, -0.27848435,  3.09374444,  0.59435683]])

In [42]:
qoldiq,asos = np.modf(arr)
print(qoldiq,end="\n\n\n\n")
print(asos)

[[-0.44908045 -0.85888059  0.40496453 -0.02762133  0.06576493]
 [ 0.5258603  -0.65922439  0.19579734 -0.23635479  0.66762795]
 [ 0.53682092 -0.2703466  -0.23485728  0.05613417 -0.41367831]
 [ 0.13546575 -0.60136672 -0.27848435  0.09374444  0.59435683]]



[[-0. -0.  0. -0.  1.]
 [ 0. -0.  2. -0.  0.]
 [ 0. -1. -1.  1. -0.]
 [ 0. -1. -0.  3.  0.]]


In [43]:
#Hulosa unary faqat bitta argument qabul qiluvchi funksiya ekan

 Binary funksiyalar - (ikkita atgument qabul qiluvchi funksiyalar)

In [45]:
#  add, multiply,maximum - funksiyalar bilan tanishamiz
arr1=np.random.randint(9,size=(3,4))
arr1

array([[0, 3, 2, 3],
       [8, 2, 2, 1],
       [8, 7, 8, 8]])

In [53]:
arr2=np.random.randint(9,size=(3,4))
arr2

array([[1, 5, 1, 8],
       [2, 4, 4, 4],
       [7, 4, 6, 3]])

In [51]:
#tepadagi funksiyalar massivlar mos elementlarini qo'shib chiqadi

In [54]:
# add - qoshish metodi
np.add(arr1,arr2)  #bir narsaga e'tibor bering ikala massiv shakli-(shape) bir xil bo'lishi kerak

array([[ 1,  8,  3, 11],
       [10,  6,  6,  5],
       [15, 11, 14, 11]])

In [55]:
# multiply - kopaytirish metodi
# bu massivlarni kopaytirish qonuniyatiga bo'ysinmaydi,shunchaki pazitsiyadosh elementlar ustida amal bajaradi
np.multiply(arr1,arr2)

array([[ 0, 15,  2, 24],
       [16,  8,  8,  4],
       [56, 28, 48, 24]])

In [56]:
# maximum - ikki massiv elemlaridan kattasini oladi
np.maximum(arr1,arr2)

array([[1, 5, 2, 8],
       [8, 4, 4, 4],
       [8, 7, 8, 8]])

In [57]:
# bu korganlarimizni oddiy usulda qilishimiz ham mumkin
#deylik massivlarni qo'shmoqchimiz
arr1+arr2

array([[ 1,  8,  3, 11],
       [10,  6,  6,  5],
       [15, 11, 14, 11]])

In [59]:
np.add(arr1,arr2)   #koirganingizdek bir-xil

array([[ 1,  8,  3, 11],
       [10,  6,  6,  5],
       [15, 11, 14, 11]])

quyidagi binary funksiyalardan hsm foydalanishimiz mumkin


1.   subtract - mos elementlarni ayiradi

1.   power - birinchi elementni ikkinchi massivda korsatilgan darajaga (son) ga oshiradi
3.   max,min


4.   mod - bolinmadan faqat   butun qismini qaytaradi






## Mantiqiy shart operatori - where

In [66]:
# where mahsus  shart operatori bo'lib u shartga ko'ra ishlaydi
cond = np.array([True,False,True,False,False,False])

In [68]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5,1.6])
yarr=np.array([2.1,2.2,2.3,2.4,2.5,2.6])

In [69]:
result = np.where(cond,xarr,yarr)  # shartga ko'ra ishlaydi,True bolsa birinchi element,False bolsa ikkinchi elementno oladi
result

array([1.1, 2.2, 1.3, 2.4, 2.5, 2.6])

In [70]:
arr=np.random.randn(4,4)
arr

array([[-0.33238223, -0.07829103, -0.33461724, -0.14846105],
       [-0.86669909,  0.53638612, -1.10209655, -2.08144403],
       [ 0.77577141, -0.44602668, -1.50621105,  1.23087247],
       [-0.77118809,  1.08455127, -0.09371019, -0.85382886]])

In [74]:
result=np.where(arr<1,1,0) #arr elementi 1 dan kichik bolsa 0,aks holda 1 qaytaradi#
result

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 1]])

In [75]:
#where ham anchagina foydali metod