## **Indeks va kesib olish**


---
                                                                                                                created by Navruzbek_Abduganiyev


In [2]:
import numpy as np

In [17]:
arr=np.arange(14)  # 1 - o'lchamli massiv yaratib oldik
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [7]:
# bu yerdan 4-8 indekslar oraligini kesib olish u-n
arr[4:8]  # usuldan foydalanamiz

array([4, 5, 6, 7])

In [9]:
# bizda arr nomli massiv bor,undan kesib olingan massivga ishlov bersak asosiy massivga ta'sir ko'rsatadi,bajaramiz

In [14]:
arr1=arr[4:8]
arr1[:]=0
arr
# ko'rib turganingizdek kesilgan massivga ishlov berdik,u assosiyga ham ta'sir qildi

array([ 0,  1,  2,  3,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13])

In [18]:
#ta'sir qilishini oldini olish uchun copy() funksiyasidan foydalanamiz
arr1=arr[4:8].copy()
arr1[:]=0
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

**2-o'lchamli massivlarda indeks va keshish**

In [20]:
#massiv yaratamiz 
arr=np.random.randint(100,size=(4,5))
arr

array([[78, 35, 36, 55, 47],
       [36, 23,  4, 29, 92],
       [97, 14, 96, 64, 45],
       [57, 15, 43, 59, 31]])

In [23]:
#deylik bizga satrdan 1:2 va ustundan 2:4 (4,29,92,96,64,45) larni kesib olmoqchimiz
arr[1:3,2:5]

array([[ 4, 29, 92],
       [96, 64, 45]])

In [24]:
#boshqa sonlarni kesib olishni  ham ko'rishimiz mumkin
arr[1,:]

array([36, 23,  4, 29, 92])

In [25]:
arr[:,1]

array([35, 23, 14, 15])

In [26]:
arr[2,2]

96

**3-o'lchamli massivlar bilan ishlaymiz**

In [28]:
arr=np.random.randint(100,size=(3,4,5))  # hullas shape(3,4,5) 
arr

array([[[91, 52,  3, 85, 40],
        [62, 83, 30, 22, 32],
        [ 3,  1, 54, 23, 82],
        [68, 52, 45, 14, 20]],

       [[89, 73, 23, 38, 73],
        [60, 77, 54, 92, 61],
        [37, 95, 26, 73, 94],
        [ 1, 96, 21, 63, 55]],

       [[11, 13, 65, 30, 28],
        [12,  9,  0, 32, 21],
        [67, 15,  6, 23, 83],
        [29, 64, 70, 68, 30]]])

In [30]:
#     3-d massivdan kesib olish ham qiyin emas 
#     Deylik bizdan birinchi o'lchmdan 2:3 satrlar 3:5 ustundagi elementlar kesib olish talabi qo'yilsin
arr[0][2:4,3:6]   # sharhlaymiz [0] nechinchi o'rindagi(bizda 3 ta bor),keyin ->[oddiy 2-d massivdan kesishga o'xshash]

array([[23, 82],
       [14, 20]])

In [31]:
#Yanada ko'proq ma'lumot olish uchun numpy.org sahifasidan ma'lumot olishingiz mumkin