# Boolean indekslash

---

                                                                                                                 created by Navruzbek_Abduganiyev

In [3]:
import numpy as np

Boolean indekslashning asosiy vazifasi katta ma'lumotlar bilan tegishlilik ma'lumotlarni ajratib olish uchun foydalaniladi.Undan Data Science sohasida keng foydalaniladi

In [31]:
countries=np.array(["UZB","USA","BAA","UK","UZB","MEX"]) #ushbu massiv uzunligi kesib olinishikerak bo'lgan arr satrlar soniga teng bo']lishi kerk
arr=np.random.randint(100,size=(6,5))
arr

array([[83, 37, 32, 26, 89],
       [97, 94, 47, 99, 80],
       [ 9, 45, 98, 93, 91],
       [58, 87, 86,  8, 25],
       [ 0, 67, 49, 62, 15],
       [20, 31, 57, 61, 85]])

In [12]:
arr[countries=="UZB"]

array([[79, 27, 81, 31, 81],
       [ 9, 97, 91, 96, 35]])

In [13]:
arr[countries==["USA"]]

array([[83, 89, 92, 44, 73]])

In [20]:
# shuningdek ixtiyoriy indeks tanlashimiz mumkin
mask=(countries=="UZB") | (countries=="USA")
arr[mask]

array([[79, 27, 81, 31, 81],
       [83, 89, 92, 44, 73],
       [ 9, 97, 91, 96, 35]])

In [32]:
# Hullas ikkita arraylardan bir - biriga contact qurish mumkin.Bu usuldan juda ko'p foydalaniladi

arr[arr<15]  # bunda ko'rinishda filtirlashni amalga oshirishimiz mumkin,va u ham foydali ham kerakli usuldir

array([9, 8, 0])

In [33]:
arr[arr>50]  #filtrlash boldimi , 1-o'lchamli massivga taxlaydi

array([83, 89, 97, 94, 99, 80, 98, 93, 91, 58, 87, 86, 67, 62, 57, 61, 85])