# **Numpy** *kutubxonasi bilan ishlaymiz*
numpydan - massivlar yaratish uchun foydalanamiz!!!

*massivlar yaratishning bir qancha usullarini ko'rib chiqamiz*

---


                                                                                                                  created by Navruzbek_Abduganiyev








In [1]:
#numpy kkutubhonasini chaqirib olamiz
import numpy as np

In [2]:
#array maxsus funksiya bo'lib,u har qanday turdagi ketma_ket ma'lumotlarni qabul qilib, uni yangi numpy arrayiga o'giradi*/
arr=np.array([1,2,3,4])  #listni qabul qildi
arr

array([1, 2, 3, 4])

In [3]:
arr=np.array((1,2,3,4,5,6)) #tuple qabul qildi
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
#shu  o'rinda ma'lumot turini ham ko'rib ketishimiz mumkin
type(arr)

numpy.ndarray

In [13]:
#arraylar bir necha o'lchamli bo'lishi ham mumkin
#array o'lchamini bilish uchun mahsus (ndim) - metodi
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(f"array - o'lchami->{arr.ndim}")

[[1 2 3 4]
 [5 6 7 8]]
array - o'lchami->2


In [36]:
# 3-o'lchamli massiv
np.arange(60).reshape(3,4,5)  

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [14]:
#shuningdek shaklini,uzunligini ham ko'rishimiz mumkin
arr.shape #shakli

(2, 4)

In [15]:
arr.size  #uzunligi

8

In [17]:
# n o'lchamli massivlar yaratishning bir necha usullari bor
#np.zeros()
np.zeros(shape=(4,5)) # 0 lardan tashkil topgan 4,5 o'lchamli massiv

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
#np.ones()
np.ones((4,5)) # 1-lardan tashkil topgan 4,5 o'lchamli massiv

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#n o'lchamli massiv yaratishda random usulidan ham foydalanishimiz mumkin
np.arange(12)  #ketma_ket tartibli 0-11 massiv yaratadi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])



1.   random.randint()

2.   random.randn()
3.   random.rand()








In [22]:
np.random.randint(25,size=(4,5))   #butun sonli tepadan 25 gacha chegara (ixtiyoriy tanlaydi)
#huddi shunday ko'rinishda qolganlarini ham uzingiz ishlati ko'rishingiz mumkin

array([[15, 20,  8, 19,  5],
       [ 5, 19,  3, 21,  6],
       [ 7, 20, 10, 15, 24],
       [11, 15,  0,  2, 23]])

In [28]:
#reshape metodi ham anchagina foydali hisoblanadi
np.arange(20).reshape(4,5) #shaklini o'zgartirib beradi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
np.empty((4,5))  #aniq qiymatga ega bo'lmagan (zeros yoki ones ga o'xshamagan) qiymat qaytaradi

array([[4.66160212e-310, 5.23709585e-322, 0.00000000e+000,
        0.00000000e+000, 7.21877049e+159],
       [1.16095484e-028, 9.01700787e+223, 3.77958589e+233,
        9.43732826e-096, 1.22842675e+213],
       [2.82963180e+161, 7.62866085e+228, 1.47229765e-052,
        7.68121519e+218, 9.30534530e+199],
       [6.32672800e+180, 4.74483502e+170, 4.59210323e-072,
        3.42134148e+180, 1.03758390e+243]])

In [ ]:
#massiv yaratishining bir qancha usullari bilan ko'rishib chiqdik